const BASE_SERVER_URL = 'http://localhost:50001/api/v1/vendor';
const GIGI_CLUB_THEME_VARIANT = 'GIGI_CLUB_THEME_VARIANT';
const GIGI_CLUB_TOKEN = 'GIGI_CLUB_TOKEN';
const GIGI_CLUB_AUTH_DATA = 'GIGI_CLUB_AUTH_DATA';

export const CONSTANTS = {
    BASE_SERVER_URL,
    GIGI_CLUB_THEME_VARIANT,
    GIGI_CLUB_AUTH_DATA,
    GIGI_CLUB_TOKEN
};
